name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        ACTIONS_RUNNER_DEBUG: "true"
        ACTIONS_STEP_DEBUG: "true"
    # These permissions are needed to interact with GitHub’s OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.11.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        # Replace the sample AWS Account IDs and IAM role names with your own
        role-to-assume: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::PRODACCTID12:role/githubactions-deployments-oidc-PROD' || github.ref == 'refs/heads/develop' && 'arn:aws:iam::DEVACCTID123:role/githubactions-deployments-oidc-DEV' }}
        role-session-name: myGitHubActions

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve